/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2012440027;

import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.AEATType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.AEAType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.LangType;

/**
 *
 * @author jaejunk
 */
public class AEATextPanel extends javax.swing.JPanel {

    /**
     * Creates new form AEATextPanel
     */
    public AEATextPanel() {
        initComponents();
    }

    //함수명 : setAEAText
    //입력 : 없음
    //출력 : LangType
    //AEAText panel의 데이터를 LangType 객체에 저장
    public LangType setAEAText() {       
       LangType lang = new LangType(); //LangType 객체 생성
       
       lang.setLang(aeaLangTextField.getText()); //aeaLang 저장(aeaText의 type)
       lang.setValue(aeaTextTextField.getText()); //aeaText 저장
       
       return lang;
    }
    
    //함수명 : loadAEAT
    //입력 : AEATType
    //출력 : 없음
    //AEAText panel에 데이터 입력
    public void loadAEAT(AEATType aeat) {
        aeaTextTextField.setText(aeat.getAEA().get(0).getAEAText().get(0).getValue()); //aeaText 입력
        aeaLangTextField.setText(aeat.getAEA().get(0).getAEAText().get(0).getLang()); //aeaLang 입력
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aeaTextTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        aeaLangTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));

        jLabel1.setText("AEAText");

        jLabel2.setText("AEAText");

        jLabel3.setText("lang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(aeaLangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel2)
                            .addGap(29, 29, 29)
                            .addComponent(aeaTextTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(aeaTextTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(aeaLangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aeaLangTextField;
    private javax.swing.JTextField aeaTextTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
