/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2012440027;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.AEATType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.HeaderType;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.text.ParseException;

/**
 *
 * @author jaejunk
 */
public class HeaderPanel extends javax.swing.JPanel {

    /**
     * Creates new form HeaderPanel
     */
    public HeaderPanel() {
        initComponents();
    }
    
    //함수명 : setHeader
    //입력 : 없음
    //출력 : HeaderType
    //header panel의 데이터를 HeaderType 객체로 변환
    public HeaderType setHeader() {
        HeaderType header = new HeaderType(); //headerType 객체 생성
        header = eventPanel1.setEvent(); //eventPanel의 데이터를 불러오기 위해 EventPanel의 setEvent method를 호출
      
        header.setEffective(stringToXMLGregorianCalendar(effectiveTextField.getText())); //effective에 데이터를 입력하기 위해 string을 XMLGregorianCalendar로 변환
        header.setExpires(stringToXMLGregorianCalendar(expiresTextField.getText())); //expires 데이터를 입력하기 위해 string을 XMLGregorianCalendar로 변환
        header.getLocation().add(locationPanel2.setLocation()); //location의 데이터를 불러오기 위해 LocationPanel의 setLocation method 호출
        
        return header;
    }
    
    //함수명 : stringToXMLGregorianCalendar
    //입력 : String
    //출력 : XMLGregorianCalendar
    //header의 expire와 effective에 데이터를 입력하기 위해 String 자료형을 XMLGregorianCalendar 자료형으로 변환
    private XMLGregorianCalendar stringToXMLGregorianCalendar(String s) {
        XMLGregorianCalendar result = null; //XMLGregorianCalendar 객체 생성
        try {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss"); //date format 설정
            Date date = simpleDateFormat.parse(s); //date 객체 생성
            GregorianCalendar gregorianCalendar = (GregorianCalendar) GregorianCalendar.getInstance(); //gregorianCalendar 객체 생성
            gregorianCalendar.setTime(date); //gregorianCalendar 의 날짜 설정
            result = DatatypeFactory.newInstance().newXMLGregorianCalendar(gregorianCalendar); //xmlgregorianclanedar 저장
        } catch (ParseException ex) {
            //Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DatatypeConfigurationException ex) {
            //Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return result;
    }
    
    //함수명 : loadAEAT
    //입력 : AEATType
    //출력 : 없음
    //header Panel에 데이터 출력
    public void loadAEAT(AEATType aeat) {
        effectiveTextField.setText(aeat.getAEA().get(0).getHeader().getEffective().toString()); //effectiveTextField에 날짜를 string으로 출력
        expiresTextField.setText(aeat.getAEA().get(0).getHeader().getExpires().toString()); //expiresTextField에 날짜를 string으로 출력
        eventPanel1.loadAEAT(aeat); //eventPanel에 데이터를 출력하기 위해 EventPanel class의 loadAEAT method 호출
        locationPanel2.loadAEAT(aeat); //LocationPanel 데이터를 출력하기 위해 LocationPanel class의 loadAEAT method 호출
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        effectiveTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        expiresTextField = new javax.swing.JTextField();
        eventPanel1 = new pkg2012440027.EventPanel();
        locationPanel2 = new pkg2012440027.LocationPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));

        jLabel1.setText("Header");

        jLabel2.setText("effective");

        jLabel3.setText("expires");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(29, 29, 29)
                            .addComponent(expiresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(effectiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(effectiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(expiresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(locationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField effectiveTextField;
    private pkg2012440027.EventPanel eventPanel1;
    private javax.swing.JTextField expiresTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private pkg2012440027.LocationPanel locationPanel2;
    // End of variables declaration//GEN-END:variables

}
