/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2012440027;

import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.AEATType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.LangType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.LiveMediaType;

/**
 *
 * @author jaejunk
 */
public class LiveMediaPanel extends javax.swing.JPanel {

    /**
     * Creates new form LiveMediaPanel
     */
    public LiveMediaPanel() {
        initComponents();
    }

    //함수명 : setLiveMediaType
    //입력 : 없음
    //출력 : LiveMediaType
    //LiveMediaPanel의 데이터를 LiveMediaType으로 출력
    public LiveMediaType setLiveMediaType() {
        LiveMediaType liveMedia = new LiveMediaType(); //LiveMedia 객체 생성
        
        liveMedia.setServiceId(Integer.valueOf(serviceIdTextField.getText())); //serviceId 저장
        liveMedia.getBsid().add(Integer.valueOf(bsidTextField.getText())); //bsid 저장
        
        LangType lang = new LangType(); //lang 객체 생성
        lang.setLang(liveMediaLangTextField.getText()); //livemedialang 저장
        lang.setValue(serviceNameTextField.getText()); //serviceName 저장
        liveMedia.getServiceName().add(lang); //serviceName에 lang 데이터 추가
        
        return liveMedia;
    }
    
    //함수명 : loadAEAT
    //입력 : AEATType
    //출력 : 없음
    //LiveMediaPanel에 데이터를 출력
    public void loadAEAT(AEATType aeat) {
        String s = String.valueOf(aeat.getAEA().get(0).getLiveMedia().getBsid()); //bsid 를 string s에 저장
        String s1 = s.replace("[", ""); //"[" string 제거
        String bsid = s1.replace("]", ""); //"]" string 제거
        bsidTextField.setText(bsid); //bsid 출력
        serviceIdTextField.setText(String.valueOf(aeat.getAEA().get(0).getLiveMedia().getServiceId())); //serviceId 출력
        serviceNameTextField.setText(aeat.getAEA().get(0).getLiveMedia().getServiceName().get(0).getValue()); //serviceName 출력
        liveMediaLangTextField.setText(aeat.getAEA().get(0).getLiveMedia().getServiceName().get(0).getLang()); //liveMediaLang 출력
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bsidTextField = new javax.swing.JTextField();
        serviceIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        serviceNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        liveMediaLangTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));

        jLabel1.setText("LiveMedia");

        jLabel2.setText("bsid");

        jLabel3.setText("serviceId");

        jLabel4.setText("ServiceName");

        jLabel5.setText("lang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)
                                .addComponent(liveMediaLangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(serviceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(serviceIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(bsidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bsidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serviceIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(serviceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(liveMediaLangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bsidTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField liveMediaLangTextField;
    private javax.swing.JTextField serviceIdTextField;
    private javax.swing.JTextField serviceNameTextField;
    // End of variables declaration//GEN-END:variables
}
