/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2012440027;

import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.AEATType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.LocationType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.LocationTypeType;

/**
 *
 * @author jaejunk
 */
public class LocationPanel extends javax.swing.JPanel {

    /**
     * Creates new form LocationPanel
     */
    public LocationPanel() {
        initComponents();
    }

    //함수명 : setLocation
    //입력 : 없음
    //출력 : LocationType
    //location panel의 데이터를 LocationType 으로 변환
    public LocationType setLocation() {
        LocationType location = new LocationType(); //location 객체 생성
        location.setValue(locationTextField.getText()); //location value 저장
        //location.setType(LocationTypeType.fromValue(locationTypeTextField.getText())); //location type 저장
        if (jRadioButton1.isSelected()) { //audience의 라디오버튼이 눌린 것에 따라 값을 저장
            location.setType(LocationTypeType.fromValue("FIPS"));
        }
        else if (jRadioButton2.isSelected()) {
            location.setType(LocationTypeType.fromValue("SGC"));
        }
        else if (jRadioButton3.isSelected()) {
            location.setType(LocationTypeType.fromValue("polygon"));
        }
        else if (jRadioButton4.isSelected()) {
            location.setType(LocationTypeType.fromValue("circle"));
        }
        
        return location;
    }
    
    //함수명 : loadAEAT
    //입력 : AEATType
    //출력 : 없음
    //location panel에 데이터 출력
    public void loadAEAT(AEATType aeat) {
        locationTextField.setText(aeat.getAEA().get(0).getHeader().getLocation().get(0).getValue()); //location value 출력
        //locationTypeTextField.setText(aeat.getAEA().get(0).getHeader().getLocation().get(0).getType().value());  //location type 출력
        String type = aeat.getAEA().get(0).getHeader().getLocation().get(0).getType().value();
        if (type.equals("FIPS")) {
            jRadioButton1.setSelected(true);
        }
        else if (type.equals("SGC")) {
            jRadioButton2.setSelected(true);
        }
        else if (type.equals("polygon")) {
            jRadioButton3.setSelected(true);
        }
        else if (type.equals("circle")) {
            jRadioButton4.setSelected(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0)));

        jLabel1.setText("Location");

        jLabel2.setText("Location");

        jLabel3.setText("type");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("FIPS");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("SGC");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("polygon");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("circle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField locationTextField;
    // End of variables declaration//GEN-END:variables
}
