/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2012440027;

import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.AEATType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.AEAType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.HeaderType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.LangType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.LiveMediaType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.LocationType;
import tag.atsc_org_2016.xmlschemas.atsc3.delivery.aeat._1.MediaType;

/**
 *
 * @author jaejunk
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    //함수명 : setAEAT
    //입력 : AEATType
    //출력 : AEATType
    //각 panel의 데이터를 AEATType으로 합쳐서 AEATJFrame으로 넘겨줌
    public AEATType setAEAT(AEATType aeat) {
        System.out.println("setAEAT");
        AEAType aea = new AEAType();
        LangType aeaText = new LangType();
        MediaType media = new MediaType();
        LocationType location = new LocationType();
        LiveMediaType liveMedia = new LiveMediaType();
        HeaderType header = new HeaderType();
        //AEATType의 데이터가 될 객체들 생성
        
        //각 panel의 set method를 호출하여 데이터 저장
        aea = aEAPanel2.saveAEA();
        header = headerPanel2.setHeader();
        aeaText = aEATextPanel1.setAEAText();
        media = mediaPanel1.setMedia();
        liveMedia = liveMediaPanel1.setLiveMediaType();
        
        //데이터들을 aeat 데이터로 합침
        aeat.getAEA().add(aea);
        aeat.getAEA().get(0).getAEAText().add(aeaText);
        aeat.getAEA().get(0).setLiveMedia(liveMedia);
        aeat.getAEA().get(0).setHeader(header);
        aeat.getAEA().get(0).getMedia().add(media);
        
        
        return aeat;
    }
    
    //함수명 : loadAEAT
    //입력 : AEATType
    //출력 : 없음
    //각 panel들의 loadAEAT method를 호출하여 GUI에 데이터 출력
    public void loadAEAT(AEATType aeat) {
        //각 panel들의 loadAEAT method를 호출
        aEAPanel2.loadAEAT(aeat);
        aEATextPanel1.loadAEAT(aeat);
        headerPanel2.loadAEAT(aeat);
        liveMediaPanel1.loadAEAT(aeat);
        mediaPanel1.loadAEAT(aeat);
    }
    
    public String getMessageFromMessagePanel() {
        String m = messagePanel1.getMessage();
        
        return m;
    }
    
    public void setMessageToMessagePanel(String message) {
        messagePanel1.setMessage(message);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aEATextPanel1 = new pkg2012440027.AEATextPanel();
        liveMediaPanel1 = new pkg2012440027.LiveMediaPanel();
        mediaPanel1 = new pkg2012440027.MediaPanel();
        headerPanel2 = new pkg2012440027.HeaderPanel();
        aEAPanel2 = new pkg2012440027.AEAPanel();
        messagePanel1 = new pkg2012440027.MessagePanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(messagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aEATextPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liveMediaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aEAPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aEAPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aEATextPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(liveMediaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mediaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkg2012440027.AEAPanel aEAPanel2;
    private pkg2012440027.AEATextPanel aEATextPanel1;
    private pkg2012440027.HeaderPanel headerPanel2;
    private pkg2012440027.LiveMediaPanel liveMediaPanel1;
    private pkg2012440027.MediaPanel mediaPanel1;
    private pkg2012440027.MessagePanel messagePanel1;
    // End of variables declaration//GEN-END:variables
}
